import React,{useState} from 'react';
import {createRoot} from 'react-dom/client';
import './style.css';
const api=import.meta.env.VITE_API_URL||'http://localhost:3000/api';
type User={id:string;username:string;email:string;role:'ADMIN'|'CAPTURADOR';active:boolean};
type Project={id:string;name:string;city:string;status:string;owner?:{email:string};expenses?:unknown[]};
function App(){const[email,setEmail]=useState(''),[password,setPassword]=useState(''),[token,setToken]=useState(''),[users,setUsers]=useState<User[]>([]),[projects,setProjects]=useState<Project[]>([]),[notice,setNotice]=useState(''),[loading,setLoading]=useState(false);const[newName,setNewName]=useState(''),[newEmail,setNewEmail]=useState(''),[newPass,setNewPass]=useState(''),[role,setRole]=useState<'ADMIN'|'CAPTURADOR'>('CAPTURADOR');
const call=async(path:string,method='GET',body?:unknown)=>{const r=await fetch(api+path,{method,headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:body?JSON.stringify(body):undefined});const d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.error||'No fue posible completar la acción');return d};
const load=async(t=token)=>{setLoading(true);try{const h={Authorization:`Bearer ${t}`};const [u,p]=await Promise.all([fetch(api+'/admin/users',{headers:h}).then(x=>x.json()),fetch(api+'/admin/legalizations',{headers:h}).then(x=>x.json())]);setUsers(Array.isArray(u)?u:[]);setProjects(Array.isArray(p)?p:[])}catch(e){setNotice(e instanceof Error?e.message:'Error al cargar')}finally{setLoading(false)}};
const login=async()=>{setLoading(true);setNotice('');try{const r=await fetch(api+'/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})}),d=await r.json();if(!r.ok)throw new Error(d.error);setToken(d.token);await load(d.token)}catch(e){setNotice(e instanceof Error?e.message:'No se pudo iniciar sesión')}finally{setLoading(false)}};
const createUser=async(e:React.FormEvent)=>{e.preventDefault();try{await call('/admin/users','POST',{username:newName,email:newEmail,password:newPass,role});setNotice('Usuario creado correctamente');setNewName('');setNewEmail('');setNewPass('');load()}catch(e){setNotice(e instanceof Error?e.message:'No se pudo crear el usuario')}};
const toggle=async(u:User)=>{try{await call(`/admin/users/${u.id}/${u.active?'deactivate':'activate'}`,'PATCH');setNotice(`Usuario ${u.active?'desactivado':'activado'}`);load()}catch(e){setNotice(e instanceof Error?e.message:'No se pudo actualizar')}};
if(!token)return <main><h1>Legalizaciones USCOM</h1><p>Panel administrador</p><input placeholder="Correo" value={email} onChange={e=>setEmail(e.target.value)}/><input type="password" placeholder="Contraseña" value={password} onChange={e=>setPassword(e.target.value)}/><button onClick={login} disabled={loading}>{loading?'Ingresando...':'Ingresar'}</button>{notice&&<p className="notice">{notice}</p>}</main>;
return <main><header><div><h1>Panel administrador</h1><p>Gestión de legalizaciones USCOM SAS</p></div><button onClick={()=>load()} disabled={loading}>Actualizar</button></header>{notice&&<p className="notice">{notice}</p>}<section><h2>Crear usuario</h2><form onSubmit={createUser} className="form"><input required placeholder="Nombre de usuario" value={newName} onChange={e=>setNewName(e.target.value)}/><input required type="email" placeholder="Correo" value={newEmail} onChange={e=>setNewEmail(e.target.value)}/><input required minLength={8} type="password" placeholder="Contraseña temporal" value={newPass} onChange={e=>setNewPass(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value as 'ADMIN'|'CAPTURADOR')}><option value="CAPTURADOR">Capturador</option><option value="ADMIN">Administrador</option></select><button type="submit">Crear usuario</button></form></section><section><h2>Usuarios</h2><table><thead><tr><th>Usuario</th><th>Correo</th><th>Rol</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.username}</td><td>{u.email}</td><td>{u.role}</td><td>{u.active?'Activo':'Inactivo'}</td><td><button className={u.active?'danger':'success'} onClick={()=>toggle(u)}>{u.active?'Desactivar':'Activar'}</button></td></tr>)}</tbody></table></section><section><h2>Legalizaciones</h2>{projects.length===0?<p className="empty">Aún no hay legalizaciones registradas.</p>:<table><thead><tr><th>Proyecto</th><th>Ciudad</th><th>Usuario</th><th>Estado</th><th>Gastos</th></tr></thead><tbody>{projects.map(p=><tr key={p.id}><td>{p.name}</td><td>{p.city}</td><td>{p.owner?.email||'—'}</td><td>{p.status}</td><td>{p.expenses?.length||0}</td></tr>)}</tbody></table>}</section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
