import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
const base=String.fromEnvironment('API_BASE_URL',defaultValue:'http://localhost:3000/api');
void main(){runApp(const App());}
class App extends StatelessWidget{const App({super.key});@override Widget build(BuildContext c){return MaterialApp(title:'Legalizaciones USCOM',theme:ThemeData(colorSchemeSeed:const Color(0xff0a4e9b),useMaterial3:true),home:const Login());}}
class Login extends StatefulWidget{const Login({super.key});@override State<Login> createState()=>_LoginState();}
class _LoginState extends State<Login>{final email=TextEditingController();final password=TextEditingController();String error='';bool busy=false;Future<void> go() async{setState(()=>busy=true);try{final r=await http.post(Uri.parse('$base/auth/login'),headers:{'Content-Type':'application/json'},body:jsonEncode({'email':email.text,'password':password.text}));final d=jsonDecode(r.body);if(r.statusCode>=400)throw Exception(d['error']);if(mounted)Navigator.pushReplacement(context,MaterialPageRoute(builder:(_)=>Projects(d['token'])));}catch(e){if(mounted)setState(()=>error=e.toString());}finally{if(mounted)setState(()=>busy=false);}}@override Widget build(BuildContext c){return Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:400),child:Column(mainAxisSize:MainAxisSize.min,children:[const Icon(Icons.receipt_long,size:72),const Text('Legalizaciones USCOM',style:TextStyle(fontSize:24,fontWeight:FontWeight.bold)),TextField(controller:email,decoration:const InputDecoration(labelText:'Correo')),TextField(controller:password,obscureText:true,decoration:const InputDecoration(labelText:'Contraseña')),const SizedBox(height:16),FilledButton(onPressed:busy?null:go,child:Text(busy?'Ingresando...':'Ingresar')),Text(error,style:const TextStyle(color:Colors.red))]))));}}
class Projects extends StatefulWidget{final String token;const Projects(this.token,{super.key});@override State<Projects> createState()=>_ProjectsState();}
class _ProjectsState extends State<Projects>{List<dynamic> items=[];String error='';@override void initState(){super.initState();load();}Future<void> load()async{try{final r=await http.get(Uri.parse('$base/projects'),headers:{'Authorization':'Bearer ${widget.token}'});final d=jsonDecode(r.body);if(r.statusCode>=400)throw Exception(d['error']);if(mounted)setState(()=>items=d);}catch(e){if(mounted)setState(()=>error=e.toString());}}@override Widget build(BuildContext c){return Scaffold(appBar:AppBar(title:const Text('Mis legalizaciones'),actions:[IconButton(onPressed:load,icon:const Icon(Icons.refresh))]),body:items.isEmpty?Center(child:Text(error.isEmpty?'No hay proyectos registrados':error)):ListView(children:items.map((p)=>ListTile(title:Text(p['name']),subtitle:Text('${p['city']} · ${p['status']}'))).toList()));}}
